SynMetal_MVC/Models/ViewMod/SearchView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SynMetal_MVC.Models.ViewMod
{
    public class SearchView
    {
        

        public Product Products;

        public NewsModel News;

        public PdfFile Files;
    }
}

SynMetal_MVC/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SynMetal_MVC.Models;
using SynMetal_MVC.Models.ViewMod;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace SynMetal_MVC.Controllers
{
    public class HomeController : Controller
    {
        SynMetalEntities db = new SynMetalEntities();

        public ActionResult changes()
        {
            Session.Add("NN", 22);
            return RedirectToAction("Index");
        }
        public ActionResult Index()
        {

            #region Creation of dummy data
            //if(!db.News.Any())
            //{ 
            //DataHelpers.CreateNews();
            //}
            //if (!db.PdfCategories.Any() && !db.ProdCategories.Any())
            //{
            //    DataHelpers.CreateCategories();
            //}
            #endregion

            #region loadLastPDFAndProductAndNews 
            try
            {
                HomeIndexView view = new HomeIndexView();
                if (db.Products.Any())
                {
                    var last = db.Products.OrderByDescending(u => u.ProductId).First();

                    view.lastProduct.Description = last.Description;
                    view.lastProduct.id = last.ProductId;
                    view.lastProduct.Name = last.Name;

                    last = null;
                }
                else
                {
                    view.lastProduct = null;
                }

                var allCategories = db.PdfCategories.ToList();
                foreach (PdfCategory pd in allCategories)
                {
                    var LastPdf1 = (from dd in db.PdfFiles.OrderByDescending(u => u.PdfId)
                                    where dd.Category.CategoryId == pd.CategoryId
                                    select dd).ToList();
                    HomeIndexView.PdfView pdf = new HomeIndexView.PdfView();

                    if (LastPdf1.Count > 0)
                    {
                        pdf.Description = LastPdf1.First().Description;
                        pdf.FileName = LastPdf1.First().FileName;
                        pdf.FilePath = LastPdf1.First().FilePath;
                        pdf.Category = LastPdf1.First().Category;
                        pdf.id = LastPdf1.First().PdfId;
                        view.LastPdf.Add(pdf);
                    }
                    

                    pdf = null;
                    LastPdf1 = null;
                }
                if(view.LastPdf.Count == 0 )
                {
                    view.LastPdf = null;
                }
                if(db.News.Any())
                { 
                view.LastNews = db.News.OrderByDescending(k => k.NewsId).Take(db.News.Count() > 5 ? 5 : 2).ToList();
                }
                else
                {
                    view.LastNews = null;
                }
                return View(view);
            }
            catch (InvalidOperationException)
            {
                return View();
            }
            #endregion



        }


        public ActionResult getPdfCategoriesPartial()
        {
            return PartialView("Partial/_getpdfCategories",db.PdfCategories.ToList());
        }



        public ActionResult AboutUsPartial()
        {

            return PartialView("Partial/_ForUs");
        }

        public ActionResult About()
        {
           
            ViewBag.Message = "Your application description page. " ;
            


            return View(db.PdfCategories.ToList());
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Search(string SearchText,int? page)
        {

            string searchstring;
            try { 
            searchstring = Request.QueryString["SearchText"] != null ? Request.QueryString["SearchText"] : "";
            }catch(HttpRequestValidationException)
            {
                searchstring = "";
            }
            List<SearchView> search = new List<SearchView>();
            if(Regex.IsMatch(searchstring.ToString(),Variables.RegexForNames))
            {
                
                var news = db.News.Where(S => S.Name.Contains(searchstring)
                || S.Description.Contains(searchstring)).ToList();
                var prods = db.Products.Where(S => S.Name.Contains(searchstring) 
                || S.Description.Contains(searchstring)).ToList();
                var files = db.PdfFiles.Where(S => S.FileName.Contains(searchstring)
                || S.Description.Contains(searchstring)).ToList();
                int CountNews = news.Count;
                int CountProds = prods.Count;
                int CountFiles = files.Count;
                int i = 0;
                int j = 0;
                int k = 0;
                while(CountNews > 0 || CountProds>0 || CountFiles>0)
                {
                    SearchView res = new SearchView();
                    if(CountNews>0)
                    {
                        res.News = news[i++];
                        CountNews--;
                    }
                    if(CountProds >0)
                    {
                        res.Products = prods[j++];
                        CountProds--;
                    }
                    if(CountFiles >0)
                    {
                        res.Files = files[k++];
                        CountFiles--;
                    }
                    search.Add(res);

                }
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                ViewBag.Search = searchstring;
                ViewBag.CountRes = search.Count;
                return View(search.ToPagedList(pageNumber,pageSize));

            }

            return View();
        }


        public ActionResult Error()
        {
            return View();
        }
    }
}

SynMetal_MVC/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SynMetal_MVC.Models;
using PagedList;

namespace SynMetal_MVC.Models
{
    public class NewsController : Controller
    {
        private SynMetalEntities db = new SynMetalEntities();

        // GET: News
        public ActionResult Index(int? page)
        {

            var result = db.News.OrderByDescending(k => k.NewsId).ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(result.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult NewsShowPartial(int? page)
        {
            var result = db.News.OrderByDescending(k => k.NewsId).ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            
            return PartialView("Partial/_NewsShow", result.ToPagedList(pageNumber, pageSize));

           
        }
        public ActionResult getAllNews()
        {
            var result = db.News.OrderByDescending(k => k.NewsId).ToList();
           

            return PartialView("Partial/_ShowAllNews", result);
        }


        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsModel newsModel = db.News.Find(id);
            if (newsModel == null)
            {
                return HttpNotFound();
            }
            return View(newsModel);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NewsId,Name,Description")] NewsModel newsModel)
        {
            if (ModelState.IsValid)
            {
                db.News.Add(newsModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(newsModel);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsModel newsModel = db.News.Find(id);
            if (newsModel == null)
            {
                return HttpNotFound();
            }
            return View(newsModel);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NewsId,Name,Description")] NewsModel newsModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(newsModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newsModel);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsModel newsModel = db.News.Find(id);
            if (newsModel == null)
            {
                return HttpNotFound();
            }
            return View(newsModel);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NewsModel newsModel = db.News.Find(id);
            db.News.Remove(newsModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SynMetal_MVC/Controllers/PdfCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SynMetal_MVC.Models;

namespace SynMetal_MVC.Controllers
{
    public class PdfCategoriesController : Controller
    {
        private SynMetalEntities db = new SynMetalEntities();

        // GET: PdfCategories
        public ActionResult Index()
        {
            return View(db.PdfCategories.ToList());
        }

        // GET: PdfCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PdfCategory pdfCategory = db.PdfCategories.Find(id);
            if (pdfCategory == null)
            {
                return HttpNotFound();
            }
            return View(pdfCategory);
        }

        // GET: PdfCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PdfCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryId,Name")] PdfCategory pdfCategory)
        {
            if (ModelState.IsValid)
            {
                db.PdfCategories.Add(pdfCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pdfCategory);
        }

        // GET: PdfCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PdfCategory pdfCategory = db.PdfCategories.Find(id);
            if (pdfCategory == null)
            {
                return HttpNotFound();
            }
            return View(pdfCategory);
        }

        // POST: PdfCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryId,Name")] PdfCategory pdfCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pdfCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pdfCategory);
        }

        // GET: PdfCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PdfCategory pdfCategory = db.PdfCategories.Find(id);
            if (pdfCategory == null)
            {
                return HttpNotFound();
            }
            return View(pdfCategory);
        }

        // POST: PdfCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PdfCategory pdfCategory = db.PdfCategories.Find(id);
            db.PdfCategories.Remove(pdfCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SynMetal_MVC/Views/Home/About.cshtml
@model IEnumerable<SynMetal_MVC.Models.PdfCategory>
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>
<div class="row right">
    <div class="col-md-5 right" style="float:right;">
        <ul class="nav nav-pills">
           
            @if (User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {

                <li role="presentation">@Html.ActionLink("Upload PDF", "Create", "PdfFiles", null, null)</li>
                <li role="presentation">@Html.ActionLink("PDF Categories", "Index", "PdfCategories", null, null)</li>


            }
            <li role="presentation">@Html.ActionLink("Pdf Files", "Index", "PdfFiles", null, null) </li>
        </ul>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-2">
        <ul id="sidemenu" class="nav nav-pills nav-stacked">
            <li role="presentation" class="active"><a href="#" data-name="ForUs">Για Εμάς</a></li>
            @foreach (var mod in Model)
            {
                <li role="presentation"><a href="#" data-name="Checked" data-id="@mod.CategoryId">@mod.Name</a></li>
            }

            @*<li role="presentation"><a href="#" data-name="InvAGM">Προσκλήση</a></li>
                <li role="presentation"><a href="#" data-name="RepBoD">Έκθεση ΔΣ</a></li>
                <li role="presentation"><a href="#" data-name="RepAcc">Έκθεση Ελεγκτων</a></li>*@

        </ul>
    </div>
    <div id="Target_Results" class="col-md-8">
        @Html.Partial("Partial/_ForUs")
    </div>
</div>

@section Scripts{



}

SynMetal_MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SynMetal_MVC/Views/Home/Index.cshtml
@model SynMetal_MVC.Models.ViewMod.HomeIndexView
@{
    ViewBag.Title = "Home Page";
}
@*@Html.ActionLink("Hit mme", "changes","Home",null)*@
<div class="jumbotron">
    <h3>@ResourceFiles.Resources.SiteName</h3>
    @*<p>@if (Session["NN"] != null)
    {
        @Session["NN"].ToString();
    }</p>*@
    
    <p class="lead">@ResourceFiles.Resources.Welcome </p>
    
</div>
<div class="container">
    <div class="row">
        @if(Model != null && Model.lastProduct != null)
        { 
        <div class="col-md-3">
           
                <div class="text-center">
                    <h2>Latest Product</h2>
                    <p>
                        @Model.lastProduct.Name
                        <br />
                        <small> @Model.lastProduct.Description </small>
                    </p>

                    <p>
                        <a class="btn btn-default"
                           href="@Url.Action("Details", "Products", new { id=Model.lastProduct.id })">Learn more &raquo;</a>
                    </p>
                </div>
           
        </div>
        }
        @if(Model != null && Model.LastNews !=null)
        { 
        <div class="col-md-6 overflow-data-y" >
            <div class="text-center">
                <h2>Latest News</h2>
                @foreach (var info in Model.LastNews)
                {
                    <div class="margin-right">
                        <h4>@info.Name</h4>
                        <p>
                            
                            <br />
                            <small> @info.Description </small>
                        </p>

                        <p>
                            <a class="btn btn-default"
                               href="@Url.Action("Details", "News", new { id = info.NewsId })">Learn more &raquo;</a>
                        </p>
                    </div>
                    }
            </div>
        </div>
        }
        @if (Model != null && Model.LastPdf != null)
        {
        <div class="col-md-3 overflow-data-y">
            
                <div class="text-center">
                    <h2>Latest Files</h2>

                    @foreach (var info in Model.LastPdf)
            {
                        <div class="margin-right">
                            <h4>@info.Category.Name</h4>
                            <p>
                                <a href="@Url.Content(info.FilePath)" target="_blank" class="btn btn-info">@info.FileName</a>
                                <br />
                                <small> @info.Description </small>
                            </p>

                            <p>
                                <a class="btn btn-default"
                                   href="@Url.Action("Details", "PdfFiles", new { id = info.id })">Learn more &raquo;</a>
                            </p>
                        </div>
                    }



                </div>
           
        </div>
        }
    </div>
    </div>

<br/>
<hr />


  

SynMetal_MVC/Views/Home/Search.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<SynMetal_MVC.Models.ViewMod.SearchView>


@{
    var SearchText = ViewBag.Search != null ? ViewBag.Search : "";
    if(SearchText != "")
    {
        ViewBag.Title = "You Searched for ' " + SearchText+" '";
    }
    else
    {
        ViewBag.Title = "Search ";
    }

    var Counts = ViewBag.CountRes != null ? ViewBag.CountRes : 0;

}
<h2>@ViewBag.Title</h2>
@if (Model != null)
{
<br /><div class="text-center">
  

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
          @Html.PagedListPager(Model, (page) => Url.Action("Search", new { page, SearchText }))
       

   </div>
<br />

<table class="table">
  
    <tr>
       <th> results @(Model.PageNumber *Model.Count) of @Counts</th>
    </tr>
    @foreach (var item in Model)
    {

        if (item.News != null)
        {
            <tr>
                <td>
                    <table class="table">
                        <tr>
                            <th>@item.News.Name</th>
                        </tr>
                        <tr>
                            <td>
                                @item.News.Description
                            </td>
                            <td>
                                @Html.ActionLink("Details","Details","News", new { id=item.News.NewsId },null)
                            </td>
                        </tr>
                    </table>

                </td>
            </tr>

        }


        if (item.Products != null)
        {
            <tr>
                <td>
                    
                        <table class="table">
                            <tr>
                                <th>@item.Products.Name</th>
                            </tr>
                            <tr>
                                <td>
                                    @item.Products.Description
                                </td>
                                <td>
                                    @Html.ActionLink("Details", "Details", "Products", new { id = item.Products.ProductId }, null)
                                </td>
                            </tr>
                        </table>



                   
                </td>
            </tr>
        }

        if (item.Files != null)
        {
            <tr>
                <td>

                    <table class="table">
                        <tr>
                            <th>@item.Files.FileName</th>
                        </tr>
                        <tr>
                            <td>
                                @item.Files.Description
                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details", "Files", new { id = item.Files.PdfId }, null)
                            </td>
                        </tr>
                    </table>



                    
                </td>
            </tr>
        }
    }

</table>

    <br /><div class="text-center">


        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, (page) => Url.Action("Search", new { page, SearchText }))


    </div>
    <br />
}