SynMetal_MVC/Controllers/ProductCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SynMetal_MVC.Models;

namespace SynMetal_MVC.Controllers
{
    public class ProductCategoriesController : Controller
    {
        private SynMetalEntities db = new SynMetalEntities();

        // GET: ProductCategories
        public ActionResult Index()
        {
            return View(db.ProdCategories.ToList());
        }

       
        // GET: ProductCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryId,Name")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.ProdCategories.Add(productCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productCategory);
        }

        // GET: ProductCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProdCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: ProductCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryId,Name")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productCategory);
        }

        // GET: ProductCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProdCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: ProductCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductCategory productCategory = db.ProdCategories.Find(id);
            db.ProdCategories.Remove(productCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SynMetal_MVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SynMetal_MVC.Models;
using System.Data.Entity.Migrations;
using System.Text.RegularExpressions;


namespace SynMetal_MVC.Controllers
{
    public class ProductsController : Controller
    {
        private SynMetalEntities db = new SynMetalEntities();

        // GET: Products
        public ActionResult Index()
        {
            var prod = db.Products.OrderByDescending(k=> k.ProductId);
            var result = prod.ToList();
           
            ViewBag.Categories = new SelectList(db.ProdCategories, "CategoryId", "Name");
            return View(result);
        }

        public ActionResult getProductsBy(int? id)
        {
            System.Threading.Thread.Sleep(5000);

            List<Product> products;
            products = Search.ByProdCategory(id);
            
            return PartialView("Partial/_ProductView",products);
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);

            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        #region photo_actions
        public ActionResult CreateUploadForm()
        {
            return PartialView("Partial/_PhotoUpEdDel",null);
        }


        public ActionResult UploadPhoto()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadPhoto([Bind(Include = "Name,Description")]  PhotoFile file)
        {
            SaveObject obj;
            try
            {
                obj = PhotoHelper.SavePhoto(Request, Server, "Product", "FileUpload");
                if (obj.isValid)
                {
                    if (ModelState.IsValid)
                    {
                        file.FilePath = obj.FilePath;


                        db.Photos.AddOrUpdate(file);
                        db.SaveChanges();
                        Session.Add("FileID", file.PhotoId);

                    }
                    else
                    {
                        return View(file);
                    }
                    //  ViewBag.ProdCategories = new SelectList(db.ProdCategories, "CategoryId", "Name");

                    string path = "";
                    PhotoEdit check = PhotoEdit.def;
                    if (Session["EditUrl"] != null)
                    {
                        check = (PhotoEdit)Enum.Parse(typeof(PhotoEdit), Session["EditUrl"].ToString());
                        Session.Remove("EditUrl");
                    }
                    int EditId = 0;
                    if (Session["EditID"] != null)
                    {
                        EditId = Regex.IsMatch(Session["EditID"].ToString(), Variables.RegexForNumbers) ?
                            Int32.Parse(Session["EditID"].ToString()) : -1;
                        Session.Remove("EditID");
                        if (EditId == -1)
                        {

                            obj.Error.Add("Edit ID Problem or Something!");
                            ViewBag.Errors = obj;

                            return View();
                        }
                    }
                    string prod = null;
                    dynamic model = null;
                    switch (check)
                    {
                        case PhotoEdit.Create:
                            ViewBag.FileName = db.Photos.Find(file.PhotoId);

                            ViewBag.ProdCategories = new SelectList(db.ProdCategories, "CategoryId", "Name");
                            path = "Create";
                            break;
                        case PhotoEdit.EditProduct:
                            TempData["FileName"] = db.Photos.Find(file.PhotoId);
                            // model = db.Products.Find();
                            prod = "Products";
                            path = "Edit";
                            break;
                        case PhotoEdit.Edit:

                            model = db.Photos.Find(file.PhotoId);
                            path = "EditPhoto";
                            break;
                        default:
                            return RedirectToAction("Index");

                    }
                    System.Web.Routing.RouteValueDictionary routeValues = new System.Web.Routing.RouteValueDictionary();
                    routeValues.Add("id",EditId);
                    
                    return RedirectToAction(path,prod,routeValues);


                    // return RedirectToAction("Create");

                }
                else
                {
                    ViewBag.Errors = obj.Error;
                    return View();
                }
            }
            catch (HttpException)
            {
                obj = new SaveObject();
                obj.isValid = false;
                obj.Error.Add("The size of the file must be below 6mb");
                return View();
            }

        }

        [HttpGet]
        public ActionResult DeletePhoto(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!Regex.IsMatch(id.ToString(), Variables.RegexForNumbers))
            {
                return Content("Problem with your Id tag!");
            }
            SaveObject Deleted = PhotoHelper.DeletePhoto((int)id, Server, false);
            if (Deleted.isValid)
            {
                return Content("The File with Name: " + Deleted.Name + " has been Deleted Successfully!!");
            }

            return PartialView("Partial/_DeletedPhoto", Deleted);
        }
        [HttpGet]
        public ActionResult EditPhoto(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhotoFile file = db.Photos.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }
        [HttpPost]
        public ActionResult EditPhoto([Bind(Include = "Name,Description")] PhotoFile editfile, int? id)
        {
            string htmlattr = "FileUpload";
            SaveObject Edit = new SaveObject();

            if (!Regex.IsMatch(id.ToString(), Variables.RegexForNumbers))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (Request.Files[htmlattr].ContentLength > 0)
            {
                Edit = PhotoHelper.EditPhoto((int)id, editfile, Request, Server, "Product", htmlattr);
            }
            else
            {
                PhotoFile file = db.Photos.Find(id);
                if (file == null)
                {
                    return HttpNotFound();
                }
                file.Description = editfile.Description;
                file.Name = editfile.Name;
                try
                {
                    db.Photos.AddOrUpdate(file);
                    db.SaveChanges();
                    Edit.isValid = true;
                }
                catch (Exception)
                {
                    Edit.Error.Add("Something happened!");
                    Edit.isValid = false;
                }
            }
            if (Edit.isValid)
            {
                string path = "";
                PhotoEdit check = PhotoEdit.def;
                if (Session["EditUrl"] != null)
                {
                    check = (PhotoEdit)Enum.Parse(typeof(PhotoEdit), Session["EditUrl"].ToString());
                    Session.Remove("EditUrl");
                }
                int EditId = 0;
                if(Session["EditID"] != null)
                {
                    EditId = Regex.IsMatch(Session["EditID"].ToString(), Variables.RegexForNumbers) ?
                        Int32.Parse(Session["EditID"].ToString()) : -1;
                    Session.Remove("EditID");
                    if(EditId == -1)
                    {
                        Edit.Error.Add("Edit ID Problem or Something!");
                        ViewBag.Edit = Edit;

                        return View();
                    }
                }

                string prod = null;
                dynamic model = null;
                switch (check)
                {
                    case PhotoEdit.Create:
                        ViewBag.FileName = db.Photos.Find(id);

                        ViewBag.ProdCategories = new SelectList(db.ProdCategories, "CategoryId", "Name");
                        path = "Create";
                        break;
                    case PhotoEdit.EditProduct:
                        TempData["FileName"] = db.Photos.Find(id);
                        // model = db.Products.Find();
                        prod = "Products";
                        path = "Edit";
                        break;
                    case PhotoEdit.Edit:

                        model = db.Photos.Find(id);
                        path = "EditPhoto";
                        break;
                    default:
                        return RedirectToAction("Index");

                }
                if(Session["FromEditProduct"] !=null)
                {
                    bool ep = bool.Parse(Session["FromEditProduct"].ToString());
                    Session.Remove("FromEditProduct");
                    if(ep)
                    {
                        path = "Edit";
                        prod = "Products";

SynMetal_MVC/Views/Products/Create.cshtml
@using SynMetal_MVC.Models
@model Product

@{
    ViewBag.Title = "Create";
    PhotoFile Files = ViewBag.FileName;
    Session.Add("EditUrl", PhotoEdit.Create);
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @Html.Partial("Partial/_PhotoUpEdDel", new PhotoFile())

        <div class="form-group">

            @Html.Label("Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              @Html.DropDownList("ProdCategories",(IEnumerable<SelectListItem>) ViewBag.ProdCategories, String.Empty, new { @class = "form-control" })
              
                @if(ViewBag.ProdCatError != null)
                { 
                <p class="text-danger">@ViewBag.ProdCatError</p>
        }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/clientFunc")
}

SynMetal_MVC/Views/Products/Delete.cshtml
@model SynMetal_MVC.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SynMetal_MVC/Views/Products/Details.cshtml
@model SynMetal_MVC.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <div class="table-responsive">
        <table class="table">
         <tr>
            <th>@Html.DisplayNameFor(model => model.Category)</th>
             <th>@Html.DisplayNameFor(model => model.Name)</th>
             <th>@Html.DisplayNameFor(model => model.Description)</th>
            
         </tr>
            <tr>
                <td>@Html.DisplayFor(model => model.Category.Name)</td>
                <td>@Html.DisplayFor(model => model.Name)</td>
                <td>@Html.DisplayFor(model => model.Description)</td>
                </tr>
            </table>
     
 @if (Model.Photo != null)
 {

                    <div class="row ">
                        <div class="col-sm-6 col-md-4 ">
                            <strong>
                          
                                <span>  @Html.DisplayNameFor(model => model.Photo) </span>
                           
                           
                            </strong>
                            </div>
                            <div class="col-sm-6 col-md-4 ">
                                <div class="thumbnail" id="results">
                                    <img src="@Url.Content(Model.Photo.FilePath)" alt="@Model.Photo.Name" />
                                    <div class="caption text-center">
                                        <h4><small>Description</small></h4>
                                        <p><em>@Model.Photo.Description</em></p>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
}
    </div>

</div>
<p>
@if (User.IsInRole("Administrator") || User.IsInRole("Moderator"))
{
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) @:|

}
    @Html.ActionLink("Back to List", "Index")
</p>

SynMetal_MVC/Views/Products/Edit.cshtml
@using SynMetal_MVC.Models
@model Product

@{
    ViewBag.Title = "Edit";

    Session.Add("EditID", Model.ProductId);
    Session.Add("EditUrl", PhotoEdit.EditProduct);
    Session.Add("FromEditProduct", true);

    PhotoFile file = null;
    if(Model.Photo != null)
    {
        file = Model.Photo;
    }
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId)
        <div id="UploadPhotoDiv">
            @if (file == null)
            { 
     @Html.Partial("Partial/_PhotoUpEdDel", new PhotoFile())
            }
            else
            {
              @Html.Partial("Partial/_PhotoUpEdDel", file)
            }
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class="control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("ProdCategories",String.Empty)
                @Html.ValidationMessageFor(model => model.Category)
                @if (ViewBag.ProdCatError != null)
                {
                    <p class="text-danger">@ViewBag.ProdCatError</p>
                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Products", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
   
}

SynMetal_MVC/Views/Products/EditPhoto.cshtml
@model SynMetal_MVC.Models.PhotoFile

@{
    ViewBag.Title = "Edit Photo";
    SynMetal_MVC.Models.PhotoFile Files = ViewBag.FileName;
   
    Session.Add("EditUrl", SynMetal_MVC.Models.PhotoEdit.Edit);

}
<h2>EditPhoto</h2>


@using (Html.BeginForm("EditPhoto/" + (Files == null ? Model.PhotoId : Files.PhotoId), "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (Files == null)
        {
            @Html.HiddenFor(model => model.PhotoId)
        }
        else
        {
            <input type="hidden" id="PhotoId" name="PhotoId" value="@Files.PhotoId" />
        }
        <div class="form-group">
            @Html.Label("Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="thumbnail">
                    <img src="@Url.Content((Files == null ?Model.FilePath : Files.FilePath))"
                         alt="@(Files == null ?Model.Name : Files.Name)">

                </div>

            </div>
        </div>
        <div class="form-group">
            @Html.Label("Upload another Photo (The old one its going to be deleted!!)", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                <input type="file" id="FileUpload" name="FileUpload" />

            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SynMetal_MVC/Views/Products/Index.cshtml
@model IEnumerable<SynMetal_MVC.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
@if (User.IsInRole("Administrator") || User.IsInRole("Moderator"))
{
    @Html.ActionLink("Create New Product", "Create") @:|
    @Html.ActionLink("Manage Product Categories", "Index", "ProductCategories",null,null)
   
}
    <dl>
        <dd>
            
           <label for="Categories">Narrow By Category</label>
            </dd>
    <dd>
            @Html.DropDownList("Categories","Show All")
        </dd>
    </dl></p>

<div id="TargetArea" class="table-hover">
   @Html.Partial("Partial/_ProductView",Model)
</div>

@section Scripts {
    @* @Scripts.Render("~/bundles/jqueryval") *@
   
    
}

SynMetal_MVC/Views/Products/UploadPhoto.cshtml
@model SynMetal_MVC.Models.PhotoFile

@{
    ViewBag.Title = "Upload Photo";
    string error;
    if ((string)(Session["ToBigFile"]) != null)
    {
        error = (string)(Session["ToBigFile"]);
        Session.Remove("ToBigFile");
    }
    else
    {
        error = null;
    }


}

<h2>View</h2>


@using (Html.BeginForm("UploadPhoto", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Upload Photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-10">
                @if (error != null)
                {
                <div class="text-danger">
                    @error
                </div>
                }
                @if (ViewBag.Errors != null)
                {
                    foreach (string Err in ViewBag.Errors)
                    {
                <div class="text-danger">
                    @Err
                </div>
                    }
                }
            </div>
            <div class="col-md-10">

                <input type="file" id="FileUpload" name="FileUpload" />

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>
    </div>



    <div>
        @Html.ActionLink("Back to Product Creation", "Create")
    </div>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}